### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by 1rfsNet** [Koenvh1/ETS2-City-Coordinate-Retriever#7]
The tool does not work for me at all.

**ets2-city-coordinate-retriever.exe:**
When I run it, it only opens the garage manager in ETS2. After that nothing happens. If I open the console before, then I see the commands, but they don't work, because there is always a simicolon at the beginning: 01:10:53.810 : <ERROR> [cmd] ';goto ssheikh' - unknown command

I guess this could be a problem with my keyboard layout. If so, then it should be mentioned in the readme that the wrong keyboard layout can cause problems.

**ETS2 Log to Coordinates.exe:**

The tool is the biggest problem for me. I have now manually tried to populate the bugs.txt file by manually typing the state names into the console and then triggering the report. Unfortunately, when running this program, it never finds even a single location. Instead, it displays the following error:

```
ssheikh - Sharm El-Sheikh
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ETS2_Log_to_Coordinates.Program.Main(String[] args) in F:\Mods\ETS2\ETS2 Map Capture Tool\ETS2-City-Coordinate-Retriever\ETS2 Log to Coordinates\Program.cs:line 114
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ETS2_Log_to_Coordinates.Program.Main(String[] args) in F:\Mods\ETS2\ETS2 Map Capture Tool\ETS2-City-Coordinate-Retriever\ETS2 Log to Coordinates\Program.cs:line 114
```
I see that it does not find the path F:\Mods\ETS2\ETS2 Map Capture Tool\ETS2-City-Coordinate-Retriever\ETS2 Log to Coordinates\Program.cs, which of course does not exist for me. In the Config file I have adjusted the paths as requested. I have downloaded the compiled version v.0.3 from 15.11.2019.

Have I done something wrong?
By the way, I use ETS2, v. 1.4.3 and wanted to get the coordinates for the map Red Sea 1.3.3 for ETS2 local radio.

**Comment by 1rfsNet** [comment]
BTW:
the name of the city file (just testing with one file for now) is ssheikh.sui (tried to rename to .sii too).
content:

```
city_data: city.ssheikh
{
	city_name: "Sharm El-Sheikh"
	city_name_localized: "@@Sharm El-Sheikh@@"
	country: egypt

	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0
	map_x_offsets[]: 0

	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0
	map_y_offsets[]: 0

	vehicle_brands[]:"scania"
	
	### MEDIUM CITY ###
    city_pin_scale_factor[]: 1.0
    city_pin_scale_factor[]: 1.0
    city_pin_scale_factor[]: 1.0  // close zoom for minimap
    city_pin_scale_factor[]: 0.8  // far zoom for monimap
    city_pin_scale_factor[]: 1.0  // city zoom for world map
    city_pin_scale_factor[]: 1.0  // closest zoom for world map
    city_pin_scale_factor[]: 1.0  // middle zoom for world map
    city_pin_scale_factor[]: 0.8  // whole world map zoom
}
```

And this is the content from the bugs file:

` ;[07/01/2022 17:30:52] (sec+0036+0039);147911;67.1992;156616;0;-1.19029`

**Comment by Koenvh1** [comment]
It could very well be that it only works with an US international keyboard layout - I have not tested it with other layouts, although it does expect the _ to be on the same key as -. It uses https://www.codeproject.com/Articles/117657/InputManager-library-Track-user-input-and-simulate, which makes no mention of it being restricted to one keyboard layout.

I presume other keyboard layouts also use tilde (`) to open the console?

What the program does is the following:
- It opens the console
- Types `goto amsterdam` (or whatever the city name is, in the case above `goto ssheikh`)
- Closes the console
- Presses F11 to open the bug report window
- Types `amsterdam`
- Presses enter to submit the bug report
- Repeat for the next city

If any of those keys are different using other keyboard layouts, then it will fail. I was under the presumption that those keys would be the same everywhere, just in a different place. Note that if the map takes too long to load, then the process messes up as well. That's what the delay is for.

Your bugs.txt seems to be missing the city name, which is what causes the error. You can see an example in one of the cities_x.txt files

**Comment by 1rfsNet** [comment]
Okay after switching to US keyboard layout it is working fine for me. This should be added to the readme. On my German keyboard, the console key is somewhere else: The key to the left of the 1 and below the Esc key.
https://image.shutterstock.com/shutterstock/photos/302271542/display_1500/stock-vector-vector-german-keyboard-layout-deutsch-302271542.jpg

So I wasn't aware that I have to add the city name to the report. Now it's working fine :)

**Comment by Koenvh1** [comment]
InputManager is an odd thing. It does press the right buttons (it does not care whether you use QWERTZ or QWERTY), but apparently these things are keyboard layout dependent. Anyway, I added it to the README (https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever/commit/d02dce2434198f21f3c772a5e47f10d867fea37b)
